user:
    name: glen
    uid: 1000
    group: glen
    shell: /usr/bin/zsh
    email:  glen.goodwin1992@gmail.com
    log:
        dir: log
        rotate: 8

hostname: Romdeau

dotfiles:
    url: git@github.com:losttenko/.dotfiles.git
    destination: /home/glen/.dotfiles

firejail:
    blacklist:
        - ~/.keys
ssh:
    port: 22
    user_key: /home/glen/.ssh/id_ed25519
    enable_sshd: True

gnupg:
    enable_agent: True
    emulate_ssh: True

base_packages:
    - base-devel
    - man-db
    - man-pages
    - pacman-contrib
    - fwupd
    - dmidecode
    - tmux
    - git
    - rsync
    - coreutils
    - moreutils
    - dateutils
    - bc
    - ranger
    - arch-wiki-lite
    - arch-wiki-docs
    - python-keyring
    - python-secretstorage
    - tig
    - ruby
    - pv
    - minicom
    - jq
    - termdown
    - fzf
    - cpulimit

aur:
    dir: aur
    packages:
        - yay
        - downgrade
        - zplug
        - miller
        - myrepos
        - ctmg
bluetooth:
    disable: False

dev:
  base:
   - arm-none-eabi-binutils
   - arm-none-eabi-gcc
   - arm-none-eabi-newlib
   - avrdude
   - avr-gcc
   - avr-libc
   - bash-language-server
   - cmake
   - colordiff
   - devhelp
   - dfu-programmer
   - dfu-util
   - docker
   - docker-compose
   - eslint
   - fakeroot
   - flex
   - groff
   - highlight
   - hlint
   - hyperfine
   - make
   - marked
   - nim
   - nimble
   - pandoc
   - picocom
   - pyenv
   - pyenv-virtualenv
   - python-black
   - python-isort
   - python-nose
   - python-pip
   - python-pipenv
   - python-pylint
   - python-pynvim
   - python-pytest
   - python-pyflakes
   - pyright
   - qmk
   - ripgrep
   - rust
   - shellcheck
   - texlive-most
  aur:
   - cc65
   - insomnia

terminal:
  base:
  aur:
