---
- hosts: localhost
  become: yes
  roles:
    - { role: aur_builder, tags: ['aur_builder'] }
    - { role: base, tags: ['base'] }
    - { role: cron, tags: ['cron'] }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: aur_builder, tags: ['aur_builder'] }
    - { role: sound, tags: ['sound'] }
    - { role: bluetooth, tags: ['bluetooth'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: alacritty, tags: ['alacritty'] }
    - { role: yubikey, tags: ['yubikey'] }
    - { role: hashicorp, tags: ['hashicorp'] }
    - { role: dev, tags: ['dev'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
