---
- name: Install bluetooth libraries and tools
  pacman:
    name:
      - bluez-openrc
      - bluez-libs
      - bluez-utils
      - blueman
    state: present

- name: Do not auto power on the bluetooth device
  command: gsettings set org.blueman.plugins.powermanager auto-power-on false
  become: yes
  become_user: "{{ user.name }}"

- name: Unblock the bluetooth service
  ansible.builtin.service:
    name: rfkill-block@bluetoothd
    enabled: no
    state: stopped
  when: bluetooth.disable == False

- name: Enable and start the bluetooth service
  ansible.builtin.service:
    name: bluetoothd
    enabled: yes
    state: started
  when: bluetooth.disable == False

- name: Disable and stop the bluetooth service
  ansible.builtin.service:
    name: bluetoothd
    enabled: no
    state: stopped
  when: bluetooth.disable == True

- name: Block the bluetooth service
  ansible.builtin.service:
    name: rfkill-block@bluetoothd
    enabled: yes
    state: started
  when: bluetooth.disable == True
