---
- name: Install universal dev packages
  pacman:
      name: "{{ dev.base }}"
      state: present
  tags:
    - packages
    - dev

- name: Install AUR dev packages
  kewlfft.aur.aur:
    use: yay
    name: "{{ dev.aur }}"
  become_user: aur_builder
  tags:
    - aur
    - packages
    - dev
