---
- name: Install Neovim
  pacman: name=neovim state=present

- name: This command will change the working directory to somedir/
  ansible.builtin.shell:
    cmd: bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)
    chdir: /home/{{user.name}}/
